### PR TITLE
Improvements: gitignore, Device Names as sources, Dry Run

### PR DESCRIPTION
**Pull request by margau**
This PR adds the following features:
- gitignore for venv etc.
- Allow Device Names to be specified as source for domains/IPs.
If this is activated, Devices are expected to have an FQDN, and their primary IPv4/IPv6 is used.
- DryRun: Only print records, but don't create/delete them.

### CODE REVIEW

**Comment by v0tti** [comment]
Looks good to me. I will test this on Monday and merge if everything is running smoothly :).

**Comment by v0tti** [comment]
I did some small correction to code structure and replaced the device filter `name__ic` (Contains (case-insensitive)) with `name__iew` (Ends with (case-insensitive)). Could you check if this still fulfills your needs?

**Comment by margau** [comment]
Looks good, works in my setup.
I additionally added the functionality for devices also for VMs.

**Comment by v0tti** [comment]
I did some small correction to code structure again and replaced the VM filter with `__iew`.
Maybe the steps for VMs and devices could be merged into a function as they are pretty much the same. On the other hand this whole script should probably be rewritten if we start using functions. Maybe I will do that in some time.

I will merge this now.

**Pull request merged**
